import 'package:flutter/material.dart';
import '../generatedscreen2widget/generated/GeneratedEllipse1Widget.dart';
import 'generated/Generated5thHoleWidget.dart';
import 'generated/GeneratedGroup43Widget1.dart';
import 'generated/GeneratedGroup77Widget.dart';
import 'generated/GeneratedGroup83Widget.dart';
import 'generated/GeneratedGroup85Widget.dart';
import 'generated/GeneratedHCPWidget.dart';
import 'generated/GeneratedLine3Widget.dart';
import 'generated/GeneratedLine4Widget.dart';
import 'generated/GeneratedRectangle12Widget.dart';
import 'generated/GeneratedRectangle5Widget1.dart';
import 'generated/GeneratedScoreWidget.dart';


/* Frame Screen3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return Stack(children: [
          Container(
              width: constraints.maxWidth,
              child: Container(

                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(32.0),
                ),
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    clipBehavior: Clip.none,
                    children: [
                      Image.asset(
                        "assets/images/ecf3a9388c58ee81a9d0534630191926ed3f4cdf.png",

                        fit: BoxFit.fitHeight,
                      ),
                      Positioned(
                        left: 24.0,
                        top: 25.0,


                        child: GestureDetector(
                          onTap: (){
                            Navigator.pop(context);
                          },
                          child: TopBackButton(),
                        ),
                      ),
                      Positioned(
                        left: 4.0,
                        top: 650.0,


                        child: GestureDetector(
                          onTap: (){
                            Navigator.pushNamed(context, "/GeneratedScreen1Widget");
                          },
                          child: GeneratedRectangle5Widget1(),
                        )
                      ),

                      Positioned(
                        left: 38.0,
                        top: 650.0,


                        child: GeneratedGroup43Widget1(),
                      ),
                      Positioned(
                        left: 244,
                        top: 70,


                        child: GeneratedGroup77Widget(),
                      ),
                      Positioned(
                        left: 61.0,
                        top: 159.0,

                        child: GeneratedGroup85Widget(),
                      ),
                      Positioned(
                        left: 60.0,
                        top: 283.0,
                         child: GeneratedGroup83Widget(),
                      ),
                      Positioned(
                        left: 132.0,
                        top: 700.0,

                        child: Generated5thHoleWidget(),
                      ),
                      Positioned(
                        left: 254.0,
                        top: 700.0,


                        child: GeneratedScoreWidget(),
                      ),
                      Positioned(
                        left: 340.0,
                        top: 700.0,


                        child: GeneratedHCPWidget(),
                      ),
                      Positioned(
                        left: 236.0,
                        top: 720,

                        child: GeneratedLine3Widget(),
                      ),
                      Positioned(
                        left: 320.0,
                        top: 720,


                        child: GeneratedLine4Widget(),
                      ),
                      Positioned(
                        top: 84.0,


                        child: GeneratedRectangle12Widget(),
                      )
                    ]),
              ))
        ]);
      }),
    ));
  }
}
