import 'package:flutter/material.dart';


/* Frame Screen1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
          borderRadius: BorderRadius.circular(32.0),
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
                return SingleChildScrollView(
                  scrollDirection: Axis.vertical,
                  child: Container(
                      height: 926.0,
                      child: Stack(children: [
                        Container(
                            width: constraints.maxWidth,
                            child: Container(
                              width: 428.0,
                              height: 926.0,
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(32.0),
                              ),
                              child: Stack(
                                  clipBehavior: Clip.none, fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.circular(32.0),
                                      child: Container(
                                        color: Color.fromARGB(255, 255, 255, 255),
                                      ),
                                    ),
                                  ]),
                            ))
                      ])),
                );
              }),
        ));
  }
}
