import 'package:flutter/material.dart';
import 'generated/GeneratedGroup92Widget.dart';

import 'generated/GeneratedGroup52Widget.dart';

/* Frame Screen1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedScreen1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final Size size = MediaQuery.of(context).size;
    final double height = size.height;
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(32.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SafeArea(
          child: SafeArea(
            child: Container(
                height: height * 1.18,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(

                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(32.0),
                        ),
                        child: Stack(
                            clipBehavior: Clip.none,
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.circular(32.0),
                                child: Container(
                                  color: Color.fromARGB(255, 255, 255, 255),
                                ),
                              ),
                              Positioned(
                                left: -28.00000762939453,
                                top: height / -27.9642857143 ,
                                child: allWidgets(),
                              )
                            ]),
                      ))
                ])),
          ),
        );
      }),
    ));
  }
}
